/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.bakageddy;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.InputStream;


public class App {
	public static void main(String[] args) throws Exception {
		InputStream input = App.class.getClassLoader().getResourceAsStream("input.txt");
		BufferedReader reader = new BufferedReader(new InputStreamReader(input));
		String line = reader.readLine();

		while (line != null) {
			Dial.turn(line);
			line = reader.readLine();
		}
		System.out.println(Dial.current);
		System.out.println(Dial.zero_events);
		reader.close();
	}
}

class Dial {
	public static int current = 50;
	public static int zero_events = 0;

	public static void turn(String operation) {
		int mag = Integer.parseInt(operation.substring(1));
		System.out.println("Dial: " + current + ", Magnitude: " + operation);
		if (operation.charAt(0) == 'L') {
			turnLeft(mag);
		} else {
			turnRight(mag);
		}

		if (current == 0) {
			zero_events++;
		}
	}

	public static void turnLeft(int magnitude) {
		magnitude = magnitude % 100;
		if (magnitude > current) {
			int diff = magnitude - current;
			current = 100 - diff;
		} else {
			current -= magnitude;
		}

	}

	public static void turnRight(int magnitude) {
		magnitude = magnitude % 100;
		if (magnitude > (100 - current)) {
			int diff = (magnitude + current - 100);
			current = diff;
		} else {
			current += magnitude;
		}

		if (current == 100) {
			current = 0;
		}
	}
}
