/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.bakageddy;

public class App {
    public static void main(String[] args) throws Exception {
		// Part1.run(args);
		Part2.run(args);
    }
}
